split/clear run-lint steps

diff --git a/.github/workflows/mediasoup-worker.yaml b/.github/workflows/mediasoup-worker.yaml
--- a/.github/workflows/mediasoup-worker.yaml
+++ b/.github/workflows/mediasoup-worker.yaml
@@ -172,13 +172,27 @@ jobs:
         name: pip3 install --break-system-packages invoke
         run: pip3 install --break-system-packages invoke
 
-      # Run clang-format on macOS.
-      - if: ${{ matrix.build.run-lint && startsWith(matrix.build.os, 'macos') }}
-        name: invoke -r worker lint
+      # Fail if run-lint is set for non macos.
+      - if: ${{ matrix.build.run-lint && !startsWith(matrix.build.os, 'macos') }}
+        name: fail if run-lint is set for non macos
         run: |
-          npm ci --prefix worker/scripts
+          echo "run-lint set for non macos"
+          exit 1
+
+      # Install clang-format on macos.
+      - if: ${{ matrix.build.run-lint && startsWith(matrix.build.os, 'macos') }}
+        name: brew install clang-format@21
+        run: |
           brew install clang-format@21
-          invoke -r worker lint
+
+      # We need to install npm deps of worker/scripts/package.json.
+      - if: ${{ matrix.build.run-lint }}
+        name: npm ci --prefix worker/scripts
+        run: npm ci --prefix worker/scripts --foreground-scripts
+
+      - if: ${{ matrix.build.run-lint }}
+        name: invoke -r worker lint
+        run: invoke -r worker lint
 
       - name: invoke -r worker mediasoup-worker
         run: invoke -r worker mediasoup-worker
